require "../schema/command"

module Kebab
  module Completion
    # Generates a bash completion script. Builds a `__`-joined key from the
    # non-option words typed so far, then offers that command's subcommands and
    # option flags via `compgen`.
    module Bash
      extend self

      def generate(command : ::Kebab::Schema::Command, binary : String? = nil) : String
        name = binary || command.name
        ::String.build do |io|
          io << "# " << name << " bash completion (generated by kebab)\n"
          io << '_' << name << "() {\n"
          io << "  local cur cmd i\n"
          io << "  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
          io << "  cmd=\"" << name << "\"\n"
          io << "  for ((i = 1; i < COMP_CWORD; i++)); do\n"
          io << "    case \"${COMP_WORDS[i]}\" in\n"
          io << "      -*) ;;\n"
          io << "      *) cmd=\"${cmd}__${COMP_WORDS[i]}\" ;;\n"
          io << "    esac\n"
          io << "  done\n"
          io << "  case \"$cmd\" in\n"
          arms(io, command, [name])
          io << "  esac\n"
          io << "  return 0\n"
          io << "}\n"
          io << "complete -F _" << name << ' ' << name << '\n'
        end
      end

      private def arms(io : IO, node : ::Kebab::Schema::Command, path : Array(String)) : Nil
        io << "    " << path.join("__") << ")\n"
        io << "      COMPREPLY=($(compgen -W \"" << Completion.candidate_words(node).join(' ') << "\" -- \"$cur\"))\n"
        io << "      ;;\n"
        node.subcommands.each { |subcommand| arms(io, subcommand, path + [subcommand.name]) }
      end
    end
  end
end
