require "../schema/command"

module Kebab
  module Completion
    # :nodoc:
    module Fish
      extend self

      def generate(command : ::Kebab::Schema::Command, binary : String? = nil) : String
        name = binary || command.name
        ::String.build do |io|
          io << "# " << name << " fish completion (generated by kebab)\n"
          io << "complete -c " << name << " -f\n"
          emit(io, command, name, [] of String)
        end
      end

      private def emit(io : IO, node : ::Kebab::Schema::Command, name : String, seen : Array(String)) : Nil
        guard = condition(seen, !node.subcommands.empty?)

        node.options.each do |option|
          io << "complete -c " << name
          io << " -n '" << guard << '\'' unless guard.empty?
          if short = option.short
            io << " -s " << short
          end
          io << " -l " << option.long
          io << " -d '" << escape(option.description) << '\'' unless option.description.empty?
          io << " -r" if option.takes_value?
          io << '\n'
        end

        node.subcommands.each do |subcommand|
          io << "complete -c " << name
          io << " -n '" << guard << '\'' unless guard.empty?
          io << " -a '" << subcommand.name << '\''
          io << " -d '" << escape(subcommand.summary) << '\'' unless subcommand.summary.empty?
          io << '\n'
        end

        node.subcommands.each do |subcommand|
          emit(io, subcommand, name, seen + [subcommand.name])
        end
      end

      private def condition(seen : Array(String), has_subcommands : Bool) : String
        if seen.empty?
          has_subcommands ? "__fish_use_subcommand" : ""
        else
          seen.map { |name| "__fish_seen_subcommand_from #{name}" }.join("; and ")
        end
      end

      private def escape(value : String) : String
        value.gsub('\\', "\\\\").gsub('\'', "\\'")
      end
    end
  end
end
