require "../schema/command"

module Kebab
  module Completion
    module Fish
      extend self

      def generate(command : ::Kebab::Schema::Command, binary : String? = nil) : String
        name = binary || command.name
        ::String.build do |io|
          io << "# " << name << " fish completion (generated by kebab)\n"
          valued = Completion.valued_flags(command)
          fixed = valued.compact_map { |flag, count| {flag, count} if count }.group_by { |(_, count)| count }
          variable = valued.compact_map { |flag, count| flag if count.nil? }.sort!
          io << "function __kebab_" << name << "_at\n"
          io << "  set -l tokens (commandline -opc)\n"
          io << "  set -l path\n"
          io << "  set -l skip 0\n"
          io << "  set -l greedy 0\n"
          io << "  for token in $tokens[2..-1]\n"
          io << "    if test $skip -gt 0\n"
          io << "      set skip (math $skip - 1)\n"
          io << "      continue\n"
          io << "    end\n"
          io << "    string match -q -- '-*' $token; and set greedy 0\n"
          io << "    switch $token\n"
          io << "      case '-*=*'\n"
          fixed.keys.sort!.each do |count|
            io << "      case"
            fixed[count].map { |(flag, _)| flag }.sort!.each { |flag| io << " '" << flag << '\'' }
            io << '\n'
            io << "        set skip " << count << '\n'
          end
          unless variable.empty?
            io << "      case"
            variable.each { |flag| io << " '" << flag << '\'' }
            io << '\n'
            io << "        set greedy 1\n"
          end
          io << "      case '-*'\n"
          io << "      case '*'\n"
          io << "        if test $greedy -eq 0\n"
          io << "          set -a path $token\n"
          io << "        end\n"
          io << "    end\n"
          io << "  end\n"
          io << "  test \"$path\" = \"$argv\"\n"
          io << "end\n"
          io << "complete -c " << name << " -f\n"
          emit(io, command, name, [] of String)
        end
      end

      private def emit(io : IO, node : ::Kebab::Schema::Command, name : String, path : Array(String)) : Nil
        guard = "__kebab_#{name}_at#{path.join { |segment| " #{segment}" }}"

        node.options.each do |option|
          io << "complete -c " << name
          io << " -n '" << guard << '\''
          if short = option.short
            io << " -s " << short
          end
          io << " -l " << option.long
          io << " -d '" << escape(option.description) << '\'' unless option.description.empty?
          io << " -r" if option.takes_value?
          io << '\n'
        end

        node.subcommands.each do |subcommand|
          io << "complete -c " << name
          io << " -n '" << guard << '\''
          io << " -a '" << subcommand.name << '\''
          io << " -d '" << escape(subcommand.summary) << '\'' unless subcommand.summary.empty?
          io << '\n'
        end

        node.subcommands.each do |subcommand|
          emit(io, subcommand, name, path + [subcommand.name])
        end
      end

      private def escape(value : String) : String
        value.gsub('\\', "\\\\").gsub('\'', "\\'")
      end
    end
  end
end
