require "./schema/command"

module Kebab
  # Generates shell completion scripts from a command's `Schema::Command`.
  # Built-in shells are in `Shell`.
  module Completion
    # The shells kebab ships generators for.
    enum Shell
      Fish
      Bash
      Zsh

      def generate(command : ::Kebab::Schema::Command, binary : String? = nil) : String
        name = binary || command.name
        case self
        in Fish then build_fish(command, name)
        in Bash then build_bash(command, name)
        in Zsh  then build_zsh(command, name)
        end
      end

      def file_name(binary : String) : String
        case self
        in Fish then "#{binary}.fish"
        in Bash then binary
        in Zsh  then "_#{binary}"
        end
      end

      # ----- fish -----

      private def build_fish(command : ::Kebab::Schema::Command, name : String) : String
        ::String.build do |io|
          io << "# " << name << " fish completion (generated by kebab)\n"
          io << "complete -c " << name << " -f\n"
          fish_emit(io, command, name, [] of String)
        end
      end

      private def fish_emit(io : IO, node : ::Kebab::Schema::Command, name : String, seen : Array(String)) : Nil
        condition = fish_condition(seen, !node.subcommands.empty?)

        node.options.each do |option|
          io << "complete -c " << name
          io << " -n '" << condition << '\'' unless condition.empty?
          if short = option.short
            io << " -s " << short
          end
          io << " -l " << option.long
          io << " -d '" << fish_escape(option.description) << '\'' unless option.description.empty?
          io << " -r" if option.takes_value?
          io << '\n'
        end

        node.subcommands.each do |subcommand|
          io << "complete -c " << name
          io << " -n '" << condition << '\'' unless condition.empty?
          io << " -a '" << subcommand.name << '\''
          io << " -d '" << fish_escape(subcommand.summary) << '\'' unless subcommand.summary.empty?
          io << '\n'
        end

        node.subcommands.each do |subcommand|
          fish_emit(io, subcommand, name, seen + [subcommand.name])
        end
      end

      private def fish_condition(seen : Array(String), has_subcommands : Bool) : String
        if seen.empty?
          has_subcommands ? "__fish_use_subcommand" : ""
        else
          seen.map { |name| "__fish_seen_subcommand_from #{name}" }.join("; and ")
        end
      end

      private def fish_escape(value : String) : String
        value.gsub('\\', "\\\\").gsub('\'', "\\'")
      end

      # ----- bash -----
      #
      # Builds a `__`-joined key from the non-option words typed so far, then
      # offers that command's subcommands and option flags via `compgen`.

      private def build_bash(command : ::Kebab::Schema::Command, name : String) : String
        ::String.build do |io|
          io << "# " << name << " bash completion (generated by kebab)\n"
          io << '_' << name << "() {\n"
          io << "  local cur cmd i\n"
          io << "  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
          io << "  cmd=\"" << name << "\"\n"
          io << "  for ((i = 1; i < COMP_CWORD; i++)); do\n"
          io << "    case \"${COMP_WORDS[i]}\" in\n"
          io << "      -*) ;;\n"
          io << "      *) cmd=\"${cmd}__${COMP_WORDS[i]}\" ;;\n"
          io << "    esac\n"
          io << "  done\n"
          io << "  case \"$cmd\" in\n"
          bash_arms(io, command, [name])
          io << "  esac\n"
          io << "  return 0\n"
          io << "}\n"
          io << "complete -F _" << name << ' ' << name << '\n'
        end
      end

      private def bash_arms(io : IO, node : ::Kebab::Schema::Command, path : Array(String)) : Nil
        io << "    " << path.join("__") << ")\n"
        io << "      COMPREPLY=($(compgen -W \"" << candidate_words(node).join(' ') << "\" -- \"$cur\"))\n"
        io << "      ;;\n"
        node.subcommands.each { |subcommand| bash_arms(io, subcommand, path + [subcommand.name]) }
      end

      # ----- zsh -----
      #
      # Same path-key dispatch, adding candidates with `compadd`.

      private def build_zsh(command : ::Kebab::Schema::Command, name : String) : String
        ::String.build do |io|
          io << "#compdef " << name << '\n'
          io << '_' << name << "() {\n"
          io << "  local cmd i\n"
          io << "  cmd=\"" << name << "\"\n"
          io << "  for ((i = 2; i < CURRENT; i++)); do\n"
          io << "    case \"${words[i]}\" in\n"
          io << "      -*) ;;\n"
          io << "      *) cmd=\"${cmd}__${words[i]}\" ;;\n"
          io << "    esac\n"
          io << "  done\n"
          io << "  case \"$cmd\" in\n"
          zsh_arms(io, command, [name])
          io << "  esac\n"
          io << "}\n"
          io << "if [ \"$funcstack[1]\" = \"_" << name << "\" ]; then\n"
          io << "  _" << name << " \"$@\"\n"
          io << "else\n"
          io << "  compdef _" << name << ' ' << name << '\n'
          io << "fi\n"
        end
      end

      private def zsh_arms(io : IO, node : ::Kebab::Schema::Command, path : Array(String)) : Nil
        io << "    " << path.join("__") << ")\n"
        io << "      compadd -- " << candidate_words(node).join(' ') << "\n"
        io << "      ;;\n"
        node.subcommands.each { |subcommand| zsh_arms(io, subcommand, path + [subcommand.name]) }
      end

      # ----- shared -----

      # Subcommand names plus option flags offered at a node, for the
      # word-list shells (bash, zsh).
      private def candidate_words(node : ::Kebab::Schema::Command) : Array(String)
        words = node.subcommands.map(&.name)
        node.options.each do |option|
          words << "--#{option.long}"
          if short = option.short
            words << "-#{short}"
          end
        end
        words
      end
    end
  end
end
