require "./schema/command"

module Kebab
  # Generates shell completion scripts from a `Schema::Command` tree. The IR
  # is the input, so adding a shell is a new pure function here, and users can
  # write their own generators against the same node.
  module Completion
    extend self

    # Returns a fish completion script for the command tree rooted at `schema`,
    # registered against the binary name `command`.
    def fish(schema : ::Kebab::Schema::Command, command : String) : String
      ::String.build do |io|
        io << "# fish completion for " << command << '\n'
        io << "# generated by kebab\n"
        io << "complete -c " << command << " -f\n"
        fish_emit(io, schema, command, [] of String)
      end
    end

    private def fish_emit(io : IO, node : ::Kebab::Schema::Command, command : String, seen : Array(String)) : Nil
      condition = fish_condition(seen, !node.subcommands.empty?)

      node.options.each do |option|
        io << "complete -c " << command
        io << " -n '" << condition << '\'' unless condition.empty?
        if short = option.short
          io << " -s " << short
        end
        io << " -l " << option.long
        io << " -d '" << fish_escape(option.description) << '\'' unless option.description.empty?
        io << " -r" if option.takes_value?
        io << '\n'
      end

      node.subcommands.each do |subcommand|
        io << "complete -c " << command
        io << " -n '" << condition << '\'' unless condition.empty?
        io << " -a '" << subcommand.name << '\''
        io << " -d '" << fish_escape(subcommand.summary) << '\'' unless subcommand.summary.empty?
        io << '\n'
      end

      node.subcommands.each do |subcommand|
        fish_emit(io, subcommand, command, seen + [subcommand.name])
      end
    end

    # The fish `-n` guard restricting a completion to the command's context.
    # Empty means no guard (a single command with no subcommands).
    private def fish_condition(seen : Array(String), has_subcommands : Bool) : String
      if seen.empty?
        has_subcommands ? "__fish_use_subcommand" : ""
      else
        seen.map { |name| "__fish_seen_subcommand_from #{name}" }.join("; and ")
      end
    end

    private def fish_escape(value : String) : String
      value.gsub('\\', "\\\\").gsub('\'', "\\'")
    end
  end
end
