name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - run: crystal tool format --check

  spec:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        crystal: ["1.20.0", latest, nightly]

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.crystal == 'nightly' }}

    steps:
      - uses: actions/checkout@v4

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Run specs
        run: crystal spec spec
